version: "3.8"

services:
  dspacedb:
    image: dspace/dspace-postgres-pgcrypto:dspace-9.3
    container_name: dspacedb
    environment:
      PGDATA: /pgdata
      POSTGRES_DB: dspace
      POSTGRES_USER: dspace
      POSTGRES_PASSWORD: dspace
    volumes:
      - dspace_pgdata:/pgdata
    networks:
      - dspacenet
    restart: unless-stopped
    ports:
      - "${DB_PORT:-5432}:5432"

  dspacesolr:
    image: dspace/dspace-solr:dspace-9.3
    container_name: dspacesolr
    volumes:
      - dspace_solr:/var/solr/data
    networks:
      - dspacenet
    restart: unless-stopped

  dspace-backend:
    image: dspace/dspace:dspace-9.3
    container_name: dspace-backend
    depends_on:
      - dspacedb
      - dspacesolr
    environment:
      dspace__P__server__P__url: ${URL:-http://localhost:8081}/server
      dspace__P__ui__P__url: ${URL:-http://localhost:8081}
      dspace__P__server__P__ssr__P__url: http://dspace-backend:8080/server
      db__P__url: jdbc:postgresql://dspacedb:5432/dspace
      db__P__username: dspace
      db__P__password: dspace
      solr__P__server__P__url: http://dspacesolr:8983/solr
      JAVA_OPTS: "-Xmx768m -Xms256m"
    ports:
      - "8080:8080"
    volumes:
      - dspace_assetstore:/dspace/assetstore
    networks:
      - dspacenet
    restart: unless-stopped

  dspace-frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        FRONTEND_REPO: https://github.com/STIKOM-TB-STUDENT-UNOFFICIAL/dspace-angular.git
        FRONTEND_BRANCH: main
    container_name: dspace-frontend
    depends_on:
      - dspace-backend
    environment:
      DSPACE_REST_SSL: "false"
      DSPACE_REST_HOST: dspace-backend
      DSPACE_REST_PORT: 8080
      DSPACE_REST_NAMESPACE: /server
    ports:
      - "4000:4000"
    networks:
      - dspacenet
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: dspace-nginx
    depends_on:
      - dspace-backend
      - dspace-frontend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "${PORT:-8081}:80"
    networks:
      - dspacenet
    restart: unless-stopped

networks:
  dspacenet:

volumes:
  dspace_pgdata:
  dspace_solr:
  dspace_assetstore: