# proxychains.conf untuk smtp-relay
# Membungkus koneksi keluar (ke smtp.gmail.com) melalui WARP SOCKS5

strict_chain
proxy_dns
remote_dns_subnet 224

tcp_read_time_out 15000
tcp_connect_time_out 8000

[ProxyList]
# warp = hostname container warproxy di Docker network dspacenet
socks5  warp  1080
